# Generated by Django 4.2.6 on 2023-10-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7, verbose_name='Name')),
                ('number_students', models.IntegerField(verbose_name='Number of students')),
                ('shift', models.CharField(max_length=9, verbose_name='Shift')),
            ],
        ),
    ]
